name: orban_vpn_desktop
description: Demonstrates how to use the wireguard_dart plugin.
version: 1.0.0+1

environment:
  sdk: '^3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter 

  wireguard_flutter:
    path: ./wireguard_package

  get: ^4.6.6

  # For API Call
  http: ^1.0.0

  # For Lottie Animation
  lottie: ^2.3.2

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  uuid: ^4.2.1

  intl: ^0.20.1

  ming_cute_icons: ^0.0.5

  country_flags: ^3.2.0

  url_launcher: ^6.2.2

  open_share_plus: ^1.2.0

  share_plus: ^10.1.3

  device_info_plus: ^11.1.0

  connectivity_plus: ^6.1.1

  window_manager: ^0.4.3

  rename_app: ^1.6.2

  # System tray support
  tray_manager: ^0.2.0
  
  # For platform-specific features
  ffi: ^2.1.3


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter: 
  uses-material-design: true 

  # App assets
  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400   
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500  
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 600  
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700  
        - asset: assets/fonts/Montserrat-Extrabold.ttf
          weight: 900     

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"