import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../helpers/config.dart';
import '../helpers/pref.dart';

class AppTranslations extends Translations {
  static Map<String, Map<String, String>> _translations = {
    "en": {
      "select_location": "Select Location",
      "fastest_server": "Fastest Server",
      "ip": "IP",
      "connecting_time": "Connecting Time",
      "setting": "Setting",
      "speed_test": "Speed Test",
      "notification": "Notification",
      "language": "Language",
      "protected_apps": "Add All Apps",
      "connection_report": "Connection Report",
      "terms_&_policy": "Terms & Policy",
      "privacy_policy": "Privacy Policy",
      "share": "Share",
      "subscriptions": "Subscriptions",
      "my_account": "My Account",
      "contact_support": "Contact Support",
      "upgrade_to_premium": "Upgrade to Premium",
      "download": "Download",
      "upload": "Upload",
      "locations": "Locations",
      "free": "Free",
      "premium": "Premium",
      "loading_vpns": "Loading VPNs... 😌",
      "loading_apps": "Loading Installed Apps... 😌",
      "vpn_not_found": "VPNs Not Found! 😔",
      "selecting_server": "Selecting Server...",
      "progress": "Progress",
      "time": "Time",
      "save": "Save",
      "no_ads": "No Ads",
      "enjoy_ads": "Enjoy surfing without annoying ads",
      "fast": "Fast",
      "increase_connection_speed": "Increase connection speed",
      "all_servers": "All Servers",
      "access_all_server_worldwide": "Access all server worldwide",
      "subscription_des":
          "To purchase a premium account click on the following button",
      "restore_purchase": "Restore Purchase",
      "terms_of_use": "Terms of Use (EULA)",
      "buy_now": "Buy Now",
      "welcome_back": "Welcome Back",
      "login_to_continue": "Login to continue",
      "email": "Email",
      "enter_your_valid_email": "enter your valid email",
      "password": "Password",
      "enter_your_password": "enter your password",
      "forgot_password?": "Forgot password?",
      "sign_in": "Sign in",
      "or_sign_in_with": "or sign in with",
      "register": "Register",
      "register_to_continue": "Register to continue",
      "phone": "Phone",
      "enter_your_phone_number": "enter your phone number",
      "name": "Name",
      "enter_your_name": "enter your name",
      "already_have_an_account? ": "Already have an account? ",
      "login": "Login",
      "report_des":
          "This is a summary of information from using ${Config.appName} while connected",
      "ip_address": "IP Address",
      "internet_provider": "Internet Provider",
      "location": "Location",
      "pin_code": "Pin code",
      "timezone": "Timezone",
      "logout": "Exit",
      "confirm_logout": "Confirm Exit",
      "logout_sure": "Are you sure you want to exit.? ",
      "yes": "Yes",
      "no": "No",
      "clear": "Clear",
      "delete_notification": "Delete Notification",
      "delete_notification_sure": "Are you sure to delete all notifications",
      "notication_not_found": "Notification not found",
      "enter_key_des": "Enter license key to activate premium features",
      "licence_key": "LICENSE KEY",
      "enter_key": "Enter License Key",
      "activate": "Activate",
      "enter_code": "Enter 6 Digit Code",
      "otp_des": "Enter 6 digits code that you received on your phone",
      "dont_have_an_account?": "Don't have an account? ",
      "subscription_active": "Your Subscription plan is active now",
      "time_balance": "Time Balance",
      "recharge_time": "Recharge Time",
      "account_management": "Account Management",
      "no_premium": "No Premium",
      "subscription_not_active": "Subscription is not active",
      "user_id": "User ID",
      "devices": "Devices",
      "expiry_date": "Expiry Date",
      "buy_account": "Buy Account",
      "recharge": "Recharge",
      "trial_off": "Trial period is expired",
      "please_register": "Please register to continue",
      "add_dns_record": "Add DNS Record",
      "edit_dns_record": "Edit DNS Record",
      "enter_dns_server": "Enter DNS Server",
      "enable_dns": "Enable DNS",
      "dns_processed": "DNS processed by core DNS module",
      "vpn_dns": "VPN DNS (Only IPv4/v6)",
      "mode": "Mode",
      "vpn_mode": "VPN Mode",
      "proxy_mode": "Proxy Mode",
      "cancel": "Cancel",
      "add_vpn": "Add VPN",
      "dns": "DNS",
      "dns_management": "DNS Management"
    },
    "hi": {
      "select_location": "स्थान चुनें",
      "fastest_server": "सबसे तेज़ सर्वर",
      "ip": "आईपी",
      "connecting_time": "कनेक्टिंग समय",
      "setting": "सेटिंग",
      "speed_test": "स्पीड टेस्ट",
      "notification": "सूचना",
      "language": "भाषा",
      "protected_apps": "सभी ऐप्स जोड़ें",
      "connection_report": "कनेक्शन रिपोर्ट",
      "terms_&_policy": "नियम और नीति",
      "privacy_policy": "गोपनीयता नीति",
      "share": "साझा करें",
      "subscriptions": "सदस्यता",
      "my_account": "मेरा खाता",
      "contact_support": "सहायता संपर्क करें",
      "upgrade_to_premium": "प्रीमियम में अपग्रेड करें",
      "download": "डाउनलोड",
      "upload": "अपलोड",
      "locations": "स्थान",
      "free": "नि:शुल्क",
      "premium": "प्रीमियम",
      "loading_vpns": "वीपीएन लोड हो रहे हैं... 😌",
      "loading_apps": "इंस्टॉल किए गए ऐप्स लोड हो रहे हैं... 😌",
      "vpn_not_found": "वीपीएन नहीं मिला! 😔",
      "selecting_server": "सर्वर का चयन किया जा रहा है...",
      "progress": "प्रगति",
      "time": "समय",
      "save": "सहेजें",
      "no_ads": "कोई विज्ञापन नहीं",
      "enjoy_ads": "विज्ञापन के बिना सर्फिंग का आनंद लें",
      "fast": "तेज़",
      "increase_connection_speed": "कनेक्शन गति बढ़ाएं",
      "all_servers": "सभी सर्वर",
      "access_all_server_worldwide": "दुनिया भर में सभी सर्वर तक पहुंच",
      "subscription_des":
          "प्रीमियम खाता खरीदने के लिए निम्नलिखित बटन पर क्लिक करें",
      "restore_purchase": "खरीदारी पुनर्स्थापित करें",
      "terms_of_use": "उपयोग की शर्तें (EULA)",
      "buy_now": "अभी खरीदें",
      "welcome_back": "वापसी पर स्वागत है",
      "login_to_continue": "जारी रखने के लिए लॉगिन करें",
      "email": "ईमेल",
      "enter_your_valid_email": "अपना वैध ईमेल दर्ज करें",
      "password": "पासवर्ड",
      "enter_your_password": "अपना पासवर्ड दर्ज करें",
      "forgot_password?": "पासवर्ड भूल गए?",
      "sign_in": "साइन इन करें",
      "or_sign_in_with": "या साइन इन करें",
      "register": "पंजीकरण करें",
      "register_to_continue": "जारी रखने के लिए पंजीकरण करें",
      "phone": "फ़ोन",
      "enter_your_phone_number": "अपना फ़ोन नंबर दर्ज करें",
      "name": "नाम",
      "enter_your_name": "अपना नाम दर्ज करें",
      "already_have_an_account?": "क्या पहले से एक खाता है? ",
      "login": "लॉगिन करें",
      "report_des":
          "यह ${Config.appName} का उपयोग करते समय कनेक्शन की जानकारी का सारांश है",
      "ip_address": "आईपी पता",
      "internet_provider": "इंटरनेट प्रदाता",
      "location": "स्थान",
      "pin_code": "पिन कोड",
      "timezone": "समय क्षेत्र",
      "logout": "लॉगआउट",
      "confirm_logout": "लॉगआउट की पुष्टि करें",
      "logout_sure": "क्या आप लॉगआउट करना चाहते हैं?",
      "yes": "हां",
      "no": "नहीं",
      "clear": "साफ करें",
      "delete_notification": "सूचना हटाएं",
      "delete_notification_sure": "सभी सूचनाएं हटाने की पुष्टि करें",
      "notication_not_found": "कोई सूचना नहीं मिली",
      "enter_key_des":
          "प्रीमियम सुविधाओं को सक्रिय करने के लिए लाइसेंस कुंजी दर्ज करें",
      "licence_key": "लाइसेंस कुंजी",
      "enter_key": "लाइसेंस कुंजी दर्ज करें",
      "activate": "सक्रिय करें",
      "enter_code": "6 अंकों का कोड दर्ज करें",
      "otp_des": "6 अंकों का कोड दर्ज करें जो आपको फोन पर प्राप्त हुआ है",
      "dont_have_an_account?": "खाता नहीं है? ",
      "subscription_active": "आपकी सदस्यता योजना अब सक्रिय है",
      "time_balance": "समय शेष",
      "recharge_time": "रीचार्ज समय",
      "account_management": "खाता प्रबंधन",
      "no_premium": "कोई प्रीमियम नहीं",
      "subscription_not_active": "सदस्यता सक्रिय नहीं है",
      "user_id": "उपयोगकर्ता आईडी",
      "devices": "डिवाइस",
      "expiry_date": "समाप्ति तिथि",
      "buy_account": "खाता खरीदें",
      "recharge": "रिचार्ज",
      "trial_off": "परीक्षण अवधि समाप्त हो गई है",
      "please_register": "जारी रखने के लिए कृपया पंजीकरण करें",
      "add_dns_record": "डीएनएस रिकॉर्ड जोड़ें",
      "edit_dns_record": "डीएनएस रिकॉर्ड संपादित करें",
      "enter_dns_server": "डीएनएस सर्वर दर्ज करें",
      "enable_dns": "डीएनएस सक्षम करें",
      "dns_processed": "कोर डीएनएस मॉड्यूल द्वारा संसाधित",
      "vpn_dns": "वीपीएन डीएनएस (केवल IPv4/v6)",
      "mode": "मोड",
      "vpn_mode": "वीपीएन मोड",
      "proxy_mode": "प्रॉक्सी मोड",
      "cancel": "रद्द करें",
      "add_vpn": "वीपीएन जोड़ें",
      "dns": "डीएनएस",
      "dns_management": "डीएनएस प्रबंधन"
    },
    "ru": {
      "select_location": "Выберите местоположение",
      "fastest_server": "Самый быстрый сервер",
      "ip": "IP",
      "connecting_time": "Время подключения",
      "setting": "Настройки",
      "speed_test": "Тест скорости",
      "notification": "Уведомление",
      "language": "Язык",
      "protected_apps": "Добавить все приложения",
      "connection_report": "Отчет о подключении",
      "terms_&_policy": "Условия и политика",
      "privacy_policy": "Политика конфиденциальности",
      "share": "Поделиться",
      "subscriptions": "Подписки",
      "my_account": "Мой аккаунт",
      "contact_support": "Связаться с поддержкой",
      "upgrade_to_premium": "Обновить до премиум",
      "download": "Загрузка",
      "upload": "Загрузка данных",
      "locations": "Местоположения",
      "free": "Бесплатно",
      "premium": "Премиум",
      "loading_vpns": "Загрузка VPN... 😌",
      "loading_apps": "Загрузка установленных приложений... 😌",
      "vpn_not_found": "VPN не найден! 😔",
      "selecting_server": "Выбор сервера...",
      "progress": "Прогресс",
      "time": "Время",
      "save": "Сохранить",
      "no_ads": "Без рекламы",
      "enjoy_ads": "Наслаждайтесь просмотром без раздражающей рекламы",
      "fast": "Быстро",
      "increase_connection_speed": "Увеличение скорости подключения",
      "all_servers": "Все серверы",
      "access_all_server_worldwide": "Доступ ко всем серверам по всему миру",
      "subscription_des":
          "Чтобы приобрести премиум-аккаунт, нажмите на следующую кнопку",
      "restore_purchase": "Восстановить покупку",
      "terms_of_use": "Условия использования (EULA)",
      "buy_now": "Купить сейчас",
      "welcome_back": "С возвращением",
      "login_to_continue": "Войдите, чтобы продолжить",
      "email": "Электронная почта",
      "enter_your_valid_email": "Введите ваш действительный email",
      "password": "Пароль",
      "enter_your_password": "Введите ваш пароль",
      "forgot_password?": "Забыли пароль?",
      "sign_in": "Войти",
      "or_sign_in_with": "или войдите через",
      "register": "Регистрация",
      "register_to_continue": "Зарегистрируйтесь, чтобы продолжить",
      "phone": "Телефон",
      "enter_your_phone_number": "Введите ваш номер телефона",
      "name": "Имя",
      "enter_your_name": "Введите ваше имя",
      "already_have_an_account?": "Уже есть аккаунт? ",
      "login": "Вход",
      "report_des":
          "Это сводка информации о использовании ${Config.appName} при подключении",
      "ip_address": "IP адрес",
      "internet_provider": "Интернет провайдер",
      "location": "Местоположение",
      "pin_code": "Почтовый индекс",
      "timezone": "Часовой пояс",
      "logout": "Выход",
      "confirm_logout": "Подтвердите выход",
      "logout_sure": "Вы уверены, что хотите выйти?",
      "yes": "Да",
      "no": "Нет",
      "clear": "Очистить",
      "delete_notification": "Удалить уведомление",
      "delete_notification_sure":
          "Вы уверены, что хотите удалить все уведомления?",
      "notication_not_found": "Уведомления не найдены",
      "enter_key_des":
          "Введите лицензионный ключ, чтобы активировать премиум функции",
      "licence_key": "Лицензионный ключ",
      "enter_key": "Введите лицензионный ключ",
      "activate": "Активировать",
      "enter_code": "Введите 6-значный код",
      "otp_des": "Введите 6-значный код, который вы получили на телефон",
      "dont_have_an_account?": "Нет аккаунта? ",
      "subscription_active": "Ваш план подписки теперь активен",
      "time_balance": "Баланс времени",
      "recharge_time": "Пополнить время",
      "account_management": "Управление аккаунтом",
      "no_premium": "Нет премиум",
      "subscription_not_active": "Подписка не активна",
      "user_id": "ID пользователя",
      "devices": "Устройства",
      "expiry_date": "Дата окончания",
      "buy_account": "Купить аккаунт",
      "recharge": "Пополнить",
      "trial_off": "Пробный период истек",
      "please_register": "Пожалуйста, зарегистрируйтесь, чтобы продолжить",
      "add_dns_record": "Добавить запись DNS",
      "edit_dns_record": "Редактировать запись DNS",
      "enter_dns_server": "Введите DNS сервер",
      "enable_dns": "Включить DNS",
      "dns_processed": "DNS обработан основным модулем DNS",
      "vpn_dns": "VPN DNS (только IPv4/v6)",
      "mode": "Режим",
      "vpn_mode": "Режим VPN",
      "proxy_mode": "Режим прокси",
      "cancel": "Отмена",
      "add_vpn": "Добавить VPN",
      "dns": "DNS",
      "dns_management": "Управление DNS"
    },
    "zh": {
      "select_location": "选择位置",
      "fastest_server": "最快的服务器",
      "ip": "IP",
      "connecting_time": "连接时间",
      "setting": "设置",
      "speed_test": "速度测试",
      "notification": "通知",
      "language": "语言",
      "protected_apps": "添加所有应用",
      "connection_report": "连接报告",
      "terms_&_policy": "条款和政策",
      "privacy_policy": "隐私政策",
      "share": "分享",
      "subscriptions": "订阅",
      "my_account": "我的账户",
      "contact_support": "联系支持",
      "upgrade_to_premium": "升级到高级版",
      "download": "下载",
      "upload": "上传",
      "locations": "位置",
      "free": "免费",
      "premium": "高级",
      "loading_vpns": "正在加载VPN... 😌",
      "loading_apps": "正在加载已安装的应用程序... 😌",
      "vpn_not_found": "未找到VPN! 😔",
      "selecting_server": "正在选择服务器...",
      "progress": "进度",
      "time": "时间",
      "save": "保存",
      "no_ads": "无广告",
      "enjoy_ads": "享受无广告的浏览体验",
      "fast": "快速",
      "increase_connection_speed": "提高连接速度",
      "all_servers": "所有服务器",
      "access_all_server_worldwide": "访问全球所有服务器",
      "subscription_des": "要购买高级帐户，请点击以下按钮",
      "restore_purchase": "恢复购买",
      "terms_of_use": "使用条款 (EULA)",
      "buy_now": "立即购买",
      "welcome_back": "欢迎回来",
      "login_to_continue": "登录以继续",
      "email": "电子邮件",
      "enter_your_valid_email": "输入您的有效电子邮件",
      "password": "密码",
      "enter_your_password": "输入您的密码",
      "forgot_password?": "忘记密码?",
      "sign_in": "登录",
      "or_sign_in_with": "或通过以下方式登录",
      "register": "注册",
      "register_to_continue": "注册以继续",
      "phone": "电话",
      "enter_your_phone_number": "输入您的电话号码",
      "name": "姓名",
      "enter_your_name": "输入您的姓名",
      "already_have_an_account?": "已经有账户了？",
      "login": "登录",
      "report_des": "这是连接到${Config.appName}时使用信息的摘要",
      "ip_address": "IP地址",
      "internet_provider": "互联网服务提供商",
      "location": "位置",
      "pin_code": "邮政编码",
      "timezone": "时区",
      "logout": "退出",
      "confirm_logout": "确认退出",
      "logout_sure": "您确定要退出吗?",
      "yes": "是",
      "no": "否",
      "clear": "清除",
      "delete_notification": "删除通知",
      "delete_notification_sure": "您确定要删除所有通知吗？",
      "notication_not_found": "未找到通知",
      "enter_key_des": "输入许可证密钥以激活高级功能",
      "licence_key": "许可证密钥",
      "enter_key": "输入许可证密钥",
      "activate": "激活",
      "enter_code": "输入6位代码",
      "otp_des": "输入您收到的6位代码",
      "dont_have_an_account?": "没有账户？",
      "subscription_active": "您的订阅计划现已激活",
      "time_balance": "时间余额",
      "recharge_time": "充值时间",
      "account_management": "账户管理",
      "no_premium": "无高级",
      "subscription_not_active": "订阅未激活",
      "user_id": "用户ID",
      "devices": "设备",
      "expiry_date": "到期日期",
      "buy_account": "购买账户",
      "recharge": "充值",
      "trial_off": "试用期已过",
      "please_register": "请注册以继续",
      "add_dns_record": "添加DNS记录",
      "edit_dns_record": "编辑DNS记录",
      "enter_dns_server": "输入DNS服务器",
      "enable_dns": "启用DNS",
      "dns_processed": "DNS由核心DNS模块处理",
      "vpn_dns": "VPN DNS（仅IPv4/v6）",
      "mode": "模式",
      "vpn_mode": "VPN模式",
      "proxy_mode": "代理模式",
      "cancel": "取消",
      "add_vpn": "添加VPN",
      "dns": "DNS",
      "dns_management": "DNS管理"
    },
    "ja": {
      "select_location": "場所を選択",
      "fastest_server": "最速サーバー",
      "ip": "IP",
      "connecting_time": "接続時間",
      "setting": "設定",
      "speed_test": "スピードテスト",
      "notification": "通知",
      "language": "言語",
      "protected_apps": "すべてのアプリを追加",
      "connection_report": "接続レポート",
      "terms_&_policy": "利用規約とポリシー",
      "privacy_policy": "プライバシーポリシー",
      "share": "共有",
      "subscriptions": "サブスクリプション",
      "my_account": "マイアカウント",
      "contact_support": "サポートに連絡",
      "upgrade_to_premium": "プレミアムにアップグレード",
      "download": "ダウンロード",
      "upload": "アップロード",
      "locations": "場所",
      "free": "無料",
      "premium": "プレミアム",
      "loading_vpns": "VPNを読み込み中... 😌",
      "loading_apps": "インストールされたアプリを読み込み中... 😌",
      "vpn_not_found": "VPNが見つかりません！ 😔",
      "selecting_server": "サーバーを選択中...",
      "progress": "進行状況",
      "time": "時間",
      "save": "保存",
      "no_ads": "広告なし",
      "enjoy_ads": "広告なしで快適にブラウジング",
      "fast": "高速",
      "increase_connection_speed": "接続速度を向上",
      "all_servers": "すべてのサーバー",
      "access_all_server_worldwide": "世界中のすべてのサーバーにアクセス",
      "subscription_des": "プレミアムアカウントを購入するには、次のボタンをクリックしてください",
      "restore_purchase": "購入を復元",
      "terms_of_use": "利用規約 (EULA)",
      "buy_now": "今すぐ購入",
      "welcome_back": "おかえりなさい",
      "login_to_continue": "続行するにはログインしてください",
      "email": "メール",
      "enter_your_valid_email": "有効なメールアドレスを入力してください",
      "password": "パスワード",
      "enter_your_password": "パスワードを入力してください",
      "forgot_password?": "パスワードを忘れましたか？",
      "sign_in": "サインイン",
      "or_sign_in_with": "または以下でサインイン",
      "register": "登録",
      "register_to_continue": "続行するには登録してください",
      "phone": "電話",
      "enter_your_phone_number": "電話番号を入力してください",
      "name": "名前",
      "enter_your_name": "名前を入力してください",
      "already_have_an_account?": "すでにアカウントをお持ちですか？",
      "login": "ログイン",
      "report_des": "${Config.appName}を使用した接続情報の概要です",
      "ip_address": "IPアドレス",
      "internet_provider": "インターネットプロバイダー",
      "location": "場所",
      "pin_code": "郵便番号",
      "timezone": "タイムゾーン",
      "logout": "ログアウト",
      "confirm_logout": "ログアウトを確認",
      "logout_sure": "本当にログアウトしますか？",
      "yes": "はい",
      "no": "いいえ",
      "clear": "クリア",
      "delete_notification": "通知を削除",
      "delete_notification_sure": "すべての通知を削除してもよろしいですか？",
      "notication_not_found": "通知が見つかりません",
      "enter_key_des": "ライセンスキーを入力してプレミアム機能を有効化してください",
      "licence_key": "ライセンスキー",
      "enter_key": "ライセンスキーを入力",
      "activate": "有効化",
      "enter_code": "6桁のコードを入力",
      "otp_des": "電話で受け取った6桁のコードを入力してください",
      "dont_have_an_account?": "アカウントをお持ちではありませんか？",
      "subscription_active": "サブスクリプションプランがアクティブになりました",
      "time_balance": "時間残高",
      "recharge_time": "時間をリチャージ",
      "account_management": "アカウント管理",
      "no_premium": "プレミアムなし",
      "subscription_not_active": "サブスクリプションがアクティブではありません",
      "user_id": "ユーザーID",
      "devices": "デバイス",
      "expiry_date": "有効期限",
      "buy_account": "アカウントを購入",
      "recharge": "チャージ",
      "trial_off": "試用期間が終了しました",
      "please_register": "続行するには登録してください",
      "add_dns_record": "DNSレコードを追加",
      "edit_dns_record": "DNSレコードを編集",
      "enter_dns_server": "DNSサーバーを入力",
      "enable_dns": "DNSを有効にする",
      "dns_processed": "DNSはコアDNSモジュールによって処理されました",
      "vpn_dns": "VPN DNS（IPv4/v6のみ）",
      "mode": "モード",
      "vpn_mode": "VPNモード",
      "proxy_mode": "プロキシモード",
      "cancel": "キャンセル",
      "add_vpn": "VPNを追加",
      "dns": "DNS",
      "dns_management": "DNS管理"
    },
    "ko": {
      "select_location": "위치 선택",
      "fastest_server": "가장 빠른 서버",
      "ip": "IP",
      "connecting_time": "연결 시간",
      "setting": "설정",
      "speed_test": "속도 테스트",
      "notification": "알림",
      "language": "언어",
      "protected_apps": "모든 앱 추가",
      "connection_report": "연결 보고서",
      "terms_&_policy": "약관 및 정책",
      "privacy_policy": "개인정보 보호정책",
      "share": "공유",
      "subscriptions": "구독",
      "my_account": "내 계정",
      "contact_support": "지원 연락",
      "upgrade_to_premium": "프리미엄으로 업그레이드",
      "download": "다운로드",
      "upload": "업로드",
      "locations": "위치",
      "free": "무료",
      "premium": "프리미엄",
      "loading_vpns": "VPN 로드 중... 😌",
      "loading_apps": "설치된 앱 로드 중... 😌",
      "vpn_not_found": "VPN을 찾을 수 없습니다! 😔",
      "selecting_server": "서버 선택 중...",
      "progress": "진행률",
      "time": "시간",
      "save": "저장",
      "no_ads": "광고 없음",
      "enjoy_ads": "광고 없이 서핑을 즐기세요",
      "fast": "빠름",
      "increase_connection_speed": "연결 속도 증가",
      "all_servers": "모든 서버",
      "access_all_server_worldwide": "전 세계 모든 서버에 액세스",
      "subscription_des": "프리미엄 계정을 구매하려면 아래 버튼을 클릭하세요",
      "restore_purchase": "구매 복원",
      "terms_of_use": "이용 약관 (EULA)",
      "buy_now": "지금 구매",
      "welcome_back": "다시 오신 것을 환영합니다",
      "login_to_continue": "계속하려면 로그인하세요",
      "email": "이메일",
      "enter_your_valid_email": "유효한 이메일을 입력하세요",
      "password": "비밀번호",
      "enter_your_password": "비밀번호를 입력하세요",
      "forgot_password?": "비밀번호를 잊으셨나요?",
      "sign_in": "로그인",
      "or_sign_in_with": "또는 다음으로 로그인",
      "register": "회원가입",
      "register_to_continue": "계속하려면 회원가입하세요",
      "phone": "전화번호",
      "enter_your_phone_number": "전화번호를 입력하세요",
      "name": "이름",
      "enter_your_name": "이름을 입력하세요",
      "already_have_an_account?": "이미 계정이 있으신가요?",
      "login": "로그인",
      "report_des": "${Config.appName} 연결 시 사용 정보를 요약한 내용입니다",
      "ip_address": "IP 주소",
      "internet_provider": "인터넷 제공업체",
      "location": "위치",
      "pin_code": "우편번호",
      "timezone": "시간대",
      "logout": "로그아웃",
      "confirm_logout": "로그아웃 확인",
      "logout_sure": "로그아웃하시겠습니까?",
      "yes": "예",
      "no": "아니오",
      "clear": "지우기",
      "delete_notification": "알림 삭제",
      "delete_notification_sure": "모든 알림을 삭제하시겠습니까?",
      "notication_not_found": "알림이 없습니다",
      "enter_key_des": "라이선스 키를 입력하여 프리미엄 기능을 활성화하세요",
      "licence_key": "라이선스 키",
      "enter_key": "라이선스 키 입력",
      "activate": "활성화",
      "enter_code": "6자리 코드를 입력하세요",
      "otp_des": "전화로 받은 6자리 코드를 입력하세요",
      "dont_have_an_account?": "계정이 없으신가요?",
      "subscription_active": "구독 플랜이 활성화되었습니다",
      "time_balance": "시간 잔액",
      "recharge_time": "시간 충전",
      "account_management": "계정 관리",
      "no_premium": "프리미엄 없음",
      "subscription_not_active": "구독이 활성화되지 않았습니다",
      "user_id": "사용자 ID",
      "devices": "장치",
      "expiry_date": "만료 날짜",
      "buy_account": "계정 구매",
      "recharge": "충전",
      "trial_off": "체험 기간이 만료되었습니다",
      "please_register": "계속하려면 등록하세요",
      "add_dns_record": "DNS 레코드 추가",
      "edit_dns_record": "DNS 레코드 편집",
      "enter_dns_server": "DNS 서버 입력",
      "enable_dns": "DNS 활성화",
      "dns_processed": "DNS는 핵심 DNS 모듈에 의해 처리됨",
      "vpn_dns": "VPN DNS (IPv4/v6 전용)",
      "mode": "모드",
      "vpn_mode": "VPN 모드",
      "proxy_mode": "프록시 모드",
      "cancel": "취소",
      "add_vpn": "VPN 추가",
      "dns": "DNS",
      "dns_management": "DNS 관리"
    },
    "es": {
      "select_location": "Seleccionar ubicación",
      "fastest_server": "Servidor más rápido",
      "ip": "IP",
      "connecting_time": "Tiempo de conexión",
      "setting": "Configuración",
      "speed_test": "Prueba de velocidad",
      "notification": "Notificación",
      "language": "Idioma",
      "protected_apps": "Agregar todas las aplicaciones",
      "connection_report": "Informe de conexión",
      "terms_&_policy": "Términos y política",
      "privacy_policy": "Política de privacidad",
      "share": "Compartir",
      "subscriptions": "Suscripciones",
      "my_account": "Mi cuenta",
      "contact_support": "Contactar soporte",
      "upgrade_to_premium": "Actualizar a Premium",
      "download": "Descargar",
      "upload": "Subir",
      "locations": "Ubicaciones",
      "free": "Gratis",
      "premium": "Premium",
      "loading_vpns": "Cargando VPNs... 😌",
      "loading_apps": "Cargando aplicaciones instaladas... 😌",
      "vpn_not_found": "¡VPN no encontrado! 😔",
      "selecting_server": "Seleccionando servidor...",
      "progress": "Progreso",
      "time": "Tiempo",
      "save": "Guardar",
      "no_ads": "Sin anuncios",
      "enjoy_ads": "Disfruta navegando sin anuncios molestos",
      "fast": "Rápido",
      "increase_connection_speed": "Aumentar la velocidad de conexión",
      "all_servers": "Todos los servidores",
      "access_all_server_worldwide":
          "Accede a todos los servidores a nivel mundial",
      "subscription_des":
          "Para comprar una cuenta premium, haz clic en el siguiente botón",
      "restore_purchase": "Restaurar compra",
      "terms_of_use": "Términos de uso (EULA)",
      "buy_now": "Comprar ahora",
      "welcome_back": "Bienvenido de nuevo",
      "login_to_continue": "Inicia sesión para continuar",
      "email": "Correo electrónico",
      "enter_your_valid_email": "Introduce tu correo electrónico válido",
      "password": "Contraseña",
      "enter_your_password": "Introduce tu contraseña",
      "forgot_password?": "¿Olvidaste tu contraseña?",
      "sign_in": "Iniciar sesión",
      "or_sign_in_with": "O iniciar sesión con",
      "register": "Registrarse",
      "register_to_continue": "Regístrate para continuar",
      "phone": "Teléfono",
      "enter_your_phone_number": "Introduce tu número de teléfono",
      "name": "Nombre",
      "enter_your_name": "Introduce tu nombre",
      "already_have_an_account?": "¿Ya tienes una cuenta?",
      "login": "Iniciar sesión",
      "report_des":
          "Este es un resumen de la información usada en ${Config.appName} mientras estás conectado",
      "ip_address": "Dirección IP",
      "internet_provider": "Proveedor de internet",
      "location": "Ubicación",
      "pin_code": "Código postal",
      "timezone": "Zona horaria",
      "logout": "Cerrar sesión",
      "confirm_logout": "Confirmar cierre de sesión",
      "logout_sure": "¿Estás seguro de que deseas cerrar sesión?",
      "yes": "Sí",
      "no": "No",
      "clear": "Limpiar",
      "delete_notification": "Eliminar notificación",
      "delete_notification_sure":
          "¿Estás seguro de que deseas eliminar todas las notificaciones?",
      "notication_not_found": "Notificación no encontrada",
      "enter_key_des":
          "Introduce la clave de licencia para activar las funciones premium",
      "licence_key": "CLAVE DE LICENCIA",
      "enter_key": "Introduce la clave de licencia",
      "activate": "Activar",
      "enter_code": "Introduce el código de 6 dígitos",
      "otp_des":
          "Introduce el código de 6 dígitos que recibiste en tu teléfono",
      "dont_have_an_account?": "¿No tienes una cuenta?",
      "subscription_active": "Tu plan de suscripción está activo ahora",
      "time_balance": "Saldo de tiempo",
      "recharge_time": "Recargar tiempo",
      "account_management": "Gestión de cuenta",
      "no_premium": "No Premium",
      "subscription_not_active": "La suscripción no está activa",
      "user_id": "ID de usuario",
      "devices": "Dispositivos",
      "expiry_date": "Fecha de vencimiento",
      "buy_account": "Comprar cuenta",
      "recharge": "Recargar",
      "trial_off": "El período de prueba ha expirado",
      "please_register": "Por favor, regístrate para continuar",
      "add_dns_record": "Agregar registro DNS",
      "edit_dns_record": "Editar registro DNS",
      "enter_dns_server": "Ingrese servidor DNS",
      "enable_dns": "Habilitar DNS",
      "dns_processed": "DNS procesado por el módulo DNS central",
      "vpn_dns": "VPN DNS (Solo IPv4/v6)",
      "mode": "Modo",
      "vpn_mode": "Modo VPN",
      "proxy_mode": "Modo proxy",
      "cancel": "Cancelar",
      "add_vpn": "Agregar VPN",
      "dns": "DNS",
      "dns_management": "Gestión de DNS"
    },
    "fr": {
      "select_location": "Sélectionner l'emplacement",
      "fastest_server": "Serveur le plus rapide",
      "ip": "IP",
      "connecting_time": "Temps de connexion",
      "setting": "Paramètres",
      "speed_test": "Test de vitesse",
      "notification": "Notification",
      "language": "Langue",
      "protected_apps": "Ajouter toutes les applications",
      "connection_report": "Rapport de connexion",
      "terms_&_policy": "Conditions générales et politique",
      "privacy_policy": "Politique de confidentialité",
      "share": "Partager",
      "subscriptions": "Abonnements",
      "my_account": "Mon compte",
      "contact_support": "Contacter le support",
      "upgrade_to_premium": "Passer à Premium",
      "download": "Télécharger",
      "upload": "Téléverser",
      "locations": "Emplacements",
      "free": "Gratuit",
      "premium": "Premium",
      "loading_vpns": "Chargement des VPN... 😌",
      "loading_apps": "Chargement des applications installées... 😌",
      "vpn_not_found": "VPN non trouvé! 😔",
      "selecting_server": "Sélection du serveur...",
      "progress": "Progrès",
      "time": "Temps",
      "save": "Sauvegarder",
      "no_ads": "Pas de publicités",
      "enjoy_ads": "Profitez d'une navigation sans publicités dérangeantes",
      "fast": "Rapide",
      "increase_connection_speed": "Augmenter la vitesse de connexion",
      "all_servers": "Tous les serveurs",
      "access_all_server_worldwide":
          "Accédez à tous les serveurs dans le monde",
      "subscription_des":
          "Pour acheter un compte premium, cliquez sur le bouton suivant",
      "restore_purchase": "Restaurer l'achat",
      "terms_of_use": "Conditions d'utilisation (EULA)",
      "buy_now": "Acheter maintenant",
      "welcome_back": "Content de vous revoir",
      "login_to_continue": "Connectez-vous pour continuer",
      "email": "Email",
      "enter_your_valid_email": "Entrez votre email valide",
      "password": "Mot de passe",
      "enter_your_password": "Entrez votre mot de passe",
      "forgot_password?": "Mot de passe oublié?",
      "sign_in": "Se connecter",
      "or_sign_in_with": "Ou connectez-vous avec",
      "register": "S'inscrire",
      "register_to_continue": "Inscrivez-vous pour continuer",
      "phone": "Téléphone",
      "enter_your_phone_number": "Entrez votre numéro de téléphone",
      "name": "Nom",
      "enter_your_name": "Entrez votre nom",
      "already_have_an_account?": "Vous avez déjà un compte?",
      "login": "Connexion",
      "report_des":
          "Ceci est un résumé des informations utilisées dans ${Config.appName} pendant la connexion",
      "ip_address": "Adresse IP",
      "internet_provider": "Fournisseur Internet",
      "location": "Emplacement",
      "pin_code": "Code postal",
      "timezone": "Fuseau horaire",
      "logout": "Se déconnecter",
      "confirm_logout": "Confirmer la déconnexion",
      "logout_sure": "Êtes-vous sûr de vouloir vous déconnecter?",
      "yes": "Oui",
      "no": "Non",
      "clear": "Effacer",
      "delete_notification": "Supprimer la notification",
      "delete_notification_sure":
          "Êtes-vous sûr de vouloir supprimer toutes les notifications?",
      "notication_not_found": "Notification non trouvée",
      "enter_key_des":
          "Entrez la clé de licence pour activer les fonctionnalités premium",
      "licence_key": "CLÉ DE LICENCE",
      "enter_key": "Entrez la clé de licence",
      "activate": "Activer",
      "enter_code": "Entrez le code à 6 chiffres",
      "otp_des":
          "Entrez le code à 6 chiffres que vous avez reçu sur votre téléphone",
      "dont_have_an_account?": "Vous n'avez pas de compte?",
      "subscription_active": "Votre plan d'abonnement est maintenant actif",
      "time_balance": "Solde du temps",
      "recharge_time": "Recharger le temps",
      "account_management": "Gestion du compte",
      "no_premium": "Pas de Premium",
      "subscription_not_active": "L'abonnement n'est pas actif",
      "user_id": "ID utilisateur",
      "devices": "Appareils",
      "expiry_date": "Date d'expiration",
      "buy_account": "Acheter un compte",
      "recharge": "Recharger",
      "trial_off": "La période d'essai est expirée",
      "please_register": "Veuillez vous inscrire pour continuer",
      "add_dns_record": "Ajouter un enregistrement DNS",
      "edit_dns_record": "Modifier l'enregistrement DNS",
      "enter_dns_server": "Entrez le serveur DNS",
      "enable_dns": "Activer le DNS",
      "dns_processed": "DNS traité par le module DNS central",
      "vpn_dns": "VPN DNS (IPv4/v6 uniquement)",
      "mode": "Mode",
      "vpn_mode": "Mode VPN",
      "proxy_mode": "Mode proxy",
      "cancel": "Annuler",
      "add_vpn": "Ajouter un VPN",
      "dns": "DNS",
      "dns_management": "Gestion DNS"
    },
    "tr": {
      "select_location": "Konum Seç",
      "fastest_server": "En Hızlı Sunucu",
      "ip": "IP",
      "connecting_time": "Bağlantı Süresi",
      "setting": "Ayarlar",
      "speed_test": "Hız Testi",
      "notification": "Bildirim",
      "language": "Dil",
      "protected_apps": "Tüm Uygulamaları Ekle",
      "connection_report": "Bağlantı Raporu",
      "terms_&_policy": "Şartlar ve Politikalar",
      "privacy_policy": "Gizlilik Politikası",
      "share": "Paylaş",
      "subscriptions": "Abonelikler",
      "my_account": "Hesabım",
      "contact_support": "Destekle İletişime Geç",
      "upgrade_to_premium": "Premium'a Yükselt",
      "download": "İndir",
      "upload": "Yükle",
      "locations": "Konumlar",
      "free": "Ücretsiz",
      "premium": "Premium",
      "loading_vpns": "VPN'ler Yükleniyor... 😌",
      "loading_apps": "Yüklü Uygulamalar Yükleniyor... 😌",
      "vpn_not_found": "VPN Bulunamadı! 😔",
      "selecting_server": "Sunucu Seçiliyor...",
      "progress": "İlerleme",
      "time": "Zaman",
      "save": "Kaydet",
      "no_ads": "Reklamsız",
      "enjoy_ads": "Rahatsız edici reklamlar olmadan gezintinin tadını çıkarın",
      "fast": "Hızlı",
      "increase_connection_speed": "Bağlantı hızını artır",
      "all_servers": "Tüm Sunucular",
      "access_all_server_worldwide": "Dünya çapındaki tüm sunuculara eriş",
      "subscription_des":
          "Premium bir hesap satın almak için aşağıdaki düğmeye tıklayın",
      "restore_purchase": "Satın almayı geri yükle",
      "terms_of_use": "Kullanım Şartları (EULA)",
      "buy_now": "Şimdi Satın Al",
      "welcome_back": "Tekrar Hoş Geldiniz",
      "login_to_continue": "Devam etmek için giriş yapın",
      "email": "E-posta",
      "enter_your_valid_email": "Geçerli e-posta adresinizi girin",
      "password": "Parola",
      "enter_your_password": "Parolanızı girin",
      "forgot_password?": "Parolanızı mı unuttunuz?",
      "sign_in": "Giriş Yap",
      "or_sign_in_with": "Veya ile giriş yapın",
      "register": "Kayıt Ol",
      "register_to_continue": "Devam etmek için kaydolun",
      "phone": "Telefon",
      "enter_your_phone_number": "Telefon numaranızı girin",
      "name": "Ad",
      "enter_your_name": "Adınızı girin",
      "already_have_an_account?": "Zaten hesabınız var mı?",
      "login": "Giriş Yap",
      "report_des":
          "${Config.appName} kullanarak bağlandığınızda kullanılan bilgilerin özeti",
      "ip_address": "IP Adresi",
      "internet_provider": "İnternet Sağlayıcı",
      "location": "Konum",
      "pin_code": "Posta Kodu",
      "timezone": "Zaman Dilimi",
      "logout": "Çıkış Yap",
      "confirm_logout": "Çıkış yapmayı onayla",
      "logout_sure": "Çıkış yapmak istediğinizden emin misiniz?",
      "yes": "Evet",
      "no": "Hayır",
      "clear": "Temizle",
      "delete_notification": "Bildirim Sil",
      "delete_notification_sure":
          "Tüm bildirimleri silmek istediğinizden emin misiniz?",
      "notication_not_found": "Bildirim Bulunamadı",
      "enter_key_des":
          "Premium özellikleri etkinleştirmek için lisans anahtarınızı girin",
      "licence_key": "LİSANS ANAHTARI",
      "enter_key": "Lisans anahtarını girin",
      "activate": "Aktifleştir",
      "enter_code": "6 haneli kodu girin",
      "otp_des": "Telefonunuza gelen 6 haneli kodu girin",
      "dont_have_an_account?": "Hesabınız yok mu?",
      "subscription_active": "Abonelik planınız şimdi aktif",
      "time_balance": "Zaman Bakiyesi",
      "recharge_time": "Zaman Yükle",
      "account_management": "Hesap Yönetimi",
      "no_premium": "Premium Yok",
      "subscription_not_active": "Abonelik aktif değil",
      "user_id": "Kullanıcı ID",
      "devices": "Cihazlar",
      "expiry_date": "Son Kullanma Tarihi",
      "buy_account": "Hesap Satın Al",
      "recharge": "Şarj et",
      "trial_off": "Deneme süresi sona erdi",
      "please_register": "Devam etmek için lütfen kaydolun",
      "add_dns_record": "DNS Kaydı Ekle",
      "edit_dns_record": "DNS Kaydını Düzenle",
      "enter_dns_server": "DNS Sunucusu Girin",
      "enable_dns": "DNS'yi Etkinleştir",
      "dns_processed": "DNS çekirdek DNS modülü tarafından işlendi",
      "vpn_dns": "VPN DNS (Yalnızca IPv4/v6)",
      "mode": "Mod",
      "vpn_mode": "VPN Modu",
      "proxy_mode": "Proxy Modu",
      "cancel": "İptal",
      "add_vpn": "VPN Ekle",
      "dns": "DNS",
      "dns_management": "DNS Yönetimi"
    },
    "ar": {
      "select_location": "حدد الموقع",
      "fastest_server": "أسرع خادم",
      "ip": "IP",
      "connecting_time": "وقت الاتصال",
      "setting": "الإعدادات",
      "speed_test": "اختبار السرعة",
      "notification": "إشعار",
      "language": "اللغة",
      "protected_apps": "إضافة جميع التطبيقات",
      "connection_report": "تقرير الاتصال",
      "terms_&_policy": "الشروط والسياسة",
      "privacy_policy": "سياسة الخصوصية",
      "share": "مشاركة",
      "subscriptions": "الاشتراكات",
      "my_account": "حسابي",
      "contact_support": "اتصل بالدعم",
      "upgrade_to_premium": "ترقية إلى بريميوم",
      "download": "تنزيل",
      "upload": "رفع",
      "locations": "المواقع",
      "free": "مجاني",
      "premium": "بريميوم",
      "loading_vpns": "جاري تحميل الشبكات الخاصة الافتراضية... 😌",
      "loading_apps": "جاري تحميل التطبيقات المثبتة... 😌",
      "vpn_not_found": "لم يتم العثور على الشبكة الخاصة الافتراضية! 😔",
      "selecting_server": "جارٍ اختيار الخادم...",
      "progress": "التقدم",
      "time": "الوقت",
      "save": "حفظ",
      "no_ads": "بدون إعلانات",
      "enjoy_ads": "استمتع بتصفح بدون إعلانات مزعجة",
      "fast": "سريع",
      "increase_connection_speed": "زيادة سرعة الاتصال",
      "all_servers": "جميع الخوادم",
      "access_all_server_worldwide": "الوصول إلى جميع الخوادم حول العالم",
      "subscription_des": "لشراء حساب بريميوم، انقر على الزر التالي",
      "restore_purchase": "استعادة الشراء",
      "terms_of_use": "شروط الاستخدام (EULA)",
      "buy_now": "اشترِ الآن",
      "welcome_back": "مرحبًا بعودتك",
      "login_to_continue": "قم بتسجيل الدخول للمتابعة",
      "email": "البريد الإلكتروني",
      "enter_your_valid_email": "أدخل بريدك الإلكتروني الصحيح",
      "password": "كلمة المرور",
      "enter_your_password": "أدخل كلمة المرور الخاصة بك",
      "forgot_password?": "هل نسيت كلمة المرور؟",
      "sign_in": "تسجيل الدخول",
      "or_sign_in_with": "أو تسجيل الدخول باستخدام",
      "register": "تسجيل",
      "register_to_continue": "سجل للمواصلة",
      "phone": "الهاتف",
      "enter_your_phone_number": "أدخل رقم هاتفك",
      "name": "الاسم",
      "enter_your_name": "أدخل اسمك",
      "already_have_an_account?": "هل لديك حساب بالفعل؟",
      "login": "تسجيل الدخول",
      "report_des":
          "هذه هي ملخص المعلومات من استخدام ${Config.appName} أثناء الاتصال",
      "ip_address": "عنوان IP",
      "internet_provider": "مزود الإنترنت",
      "location": "الموقع",
      "pin_code": "الرمز البريدي",
      "timezone": "المنطقة الزمنية",
      "logout": "تسجيل الخروج",
      "confirm_logout": "تأكيد تسجيل الخروج",
      "logout_sure": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      "yes": "نعم",
      "no": "لا",
      "clear": "مسح",
      "delete_notification": "حذف الإشعار",
      "delete_notification_sure": "هل أنت متأكد أنك تريد حذف جميع الإشعارات؟",
      "notication_not_found": "لم يتم العثور على إشعار",
      "enter_key_des": "أدخل مفتاح الترخيص لتفعيل الميزات المدفوعة",
      "licence_key": "مفتاح الترخيص",
      "enter_key": "أدخل مفتاح الترخيص",
      "activate": "تفعيل",
      "enter_code": "أدخل الرمز المكون من 6 أرقام",
      "otp_des": "أدخل الرمز المكون من 6 أرقام الذي تلقيته على هاتفك",
      "dont_have_an_account?": "لا تملك حسابًا؟",
      "subscription_active": "خطة الاشتراك الخاصة بك نشطة الآن",
      "time_balance": "رصيد الوقت",
      "recharge_time": "إعادة شحن الوقت",
      "account_management": "إدارة الحساب",
      "no_premium": "لا بريميوم",
      "subscription_not_active": "الاشتراك غير مفعل",
      "user_id": "معرف المستخدم",
      "devices": "الأجهزة",
      "expiry_date": "تاريخ الانتهاء",
      "buy_account": "اشترِ حسابًا",
      "recharge": "إعادة شحن",
      "trial_off": "انتهت فترة التجربة",
      "please_register": "يرجى التسجيل للمتابعة",
      "add_dns_record": "إضافة سجل DNS",
      "edit_dns_record": "تعديل سجل DNS",
      "enter_dns_server": "أدخل خادم DNS",
      "enable_dns": "تمكين DNS",
      "dns_processed": "تمت معالجة DNS بواسطة وحدة DNS الأساسية",
      "vpn_dns": "VPN DNS (IPv4/v6 فقط)",
      "mode": "الوضع",
      "vpn_mode": "وضع VPN",
      "proxy_mode": "وضع الوكيل",
      "cancel": "إلغاء",
      "add_vpn": "إضافة VPN",
      "dns": "DNS",
      "dns_management": "إدارة DNS"
    },
    "de": {
      "select_location": "Standort auswählen",
      "fastest_server": "Schnellster Server",
      "ip": "IP",
      "connecting_time": "Verbindungszeit",
      "setting": "Einstellungen",
      "speed_test": "Geschwindigkeitstest",
      "notification": "Benachrichtigung",
      "language": "Sprache",
      "protected_apps": "Alle Apps hinzufügen",
      "connection_report": "Verbindungsbericht",
      "terms_&_policy": "Allgemeine Geschäftsbedingungen und Richtlinien",
      "privacy_policy": "Datenschutzrichtlinie",
      "share": "Teilen",
      "subscriptions": "Abonnements",
      "my_account": "Mein Konto",
      "contact_support": "Support kontaktieren",
      "upgrade_to_premium": "Upgrade auf Premium",
      "download": "Herunterladen",
      "upload": "Hochladen",
      "locations": "Standorte",
      "free": "Kostenlos",
      "premium": "Premium",
      "loading_vpns": "Lade VPNs... 😌",
      "loading_apps": "Lade installierte Apps... 😌",
      "vpn_not_found": "VPN nicht gefunden! 😔",
      "selecting_server": "Wähle Server...",
      "progress": "Fortschritt",
      "time": "Zeit",
      "save": "Speichern",
      "no_ads": "Keine Werbung",
      "enjoy_ads": "Genieße das Surfen ohne störende Werbung",
      "fast": "Schnell",
      "increase_connection_speed": "Erhöhe die Verbindungsgeschwindigkeit",
      "all_servers": "Alle Server",
      "access_all_server_worldwide": "Greife auf alle Server weltweit zu",
      "subscription_des":
          "Um ein Premium-Konto zu kaufen, klicken Sie auf die folgende Schaltfläche",
      "restore_purchase": "Kauf wiederherstellen",
      "terms_of_use": "Nutzungsbedingungen (EULA)",
      "buy_now": "Jetzt kaufen",
      "welcome_back": "Willkommen zurück",
      "login_to_continue": "Melden Sie sich an, um fortzufahren",
      "email": "E-Mail",
      "enter_your_valid_email": "Geben Sie Ihre gültige E-Mail-Adresse ein",
      "password": "Passwort",
      "enter_your_password": "Geben Sie Ihr Passwort ein",
      "forgot_password?": "Passwort vergessen?",
      "sign_in": "Anmelden",
      "or_sign_in_with": "Oder melden Sie sich mit an",
      "register": "Registrieren",
      "register_to_continue": "Registrieren, um fortzufahren",
      "phone": "Telefon",
      "enter_your_phone_number": "Geben Sie Ihre Telefonnummer ein",
      "name": "Name",
      "enter_your_name": "Geben Sie Ihren Namen ein",
      "already_have_an_account?": "Haben Sie bereits ein Konto?",
      "login": "Anmelden",
      "report_des":
          "Dies ist eine Zusammenfassung der Informationen von der Nutzung von ${Config.appName} während der Verbindung",
      "ip_address": "IP-Adresse",
      "internet_provider": "Internetprovider",
      "location": "Standort",
      "pin_code": "Postleitzahl",
      "timezone": "Zeitzone",
      "logout": "Abmelden",
      "confirm_logout": "Abmeldung bestätigen",
      "logout_sure": "Sind Sie sicher, dass Sie sich abmelden möchten?",
      "yes": "Ja",
      "no": "Nein",
      "clear": "Löschen",
      "delete_notification": "Benachrichtigung löschen",
      "delete_notification_sure":
          "Sind Sie sicher, dass Sie alle Benachrichtigungen löschen möchten?",
      "notication_not_found": "Benachrichtigung nicht gefunden",
      "enter_key_des":
          "Geben Sie den Lizenzschlüssel ein, um Premium-Funktionen zu aktivieren",
      "licence_key": "LIZENZSCHLÜSSEL",
      "enter_key": "Geben Sie den Lizenzschlüssel ein",
      "activate": "Aktivieren",
      "enter_code": "Geben Sie den 6-stelligen Code ein",
      "otp_des":
          "Geben Sie den 6-stelligen Code ein, den Sie auf Ihrem Telefon erhalten haben",
      "dont_have_an_account?": "Haben Sie noch kein Konto?",
      "subscription_active": "Ihr Abonnementplan ist jetzt aktiv",
      "time_balance": "Zeitguthaben",
      "recharge_time": "Zeit aufladen",
      "account_management": "Kontoverwaltung",
      "no_premium": "Kein Premium",
      "subscription_not_active": "Abonnement ist nicht aktiv",
      "user_id": "Benutzer-ID",
      "devices": "Geräte",
      "expiry_date": "Ablaufdatum",
      "buy_account": "Konto kaufen",
      "recharge": "Aufladen",
      "trial_off": "Die Testphase ist abgelaufen",
      "please_register": "Bitte registrieren Sie sich, um fortzufahren",
      "add_dns_record": "DNS-Eintrag hinzufügen",
      "edit_dns_record": "DNS-Eintrag bearbeiten",
      "enter_dns_server": "DNS-Server eingeben",
      "enable_dns": "DNS aktivieren",
      "dns_processed": "DNS vom Kern-DNS-Modul verarbeitet",
      "vpn_dns": "VPN-DNS (Nur IPv4/v6)",
      "mode": "Modus",
      "vpn_mode": "VPN-Modus",
      "proxy_mode": "Proxy-Modus",
      "cancel": "Abbrechen",
      "add_vpn": "VPN hinzufügen",
      "dns": "DNS",
      "dns_management": "DNS-Verwaltung"
    },
    "fa": {
      "select_location": "انتخاب مکان",
      "fastest_server": "سریع‌ترین سرور",
      "ip": "آی‌پی",
      "connecting_time": "زمان اتصال",
      "setting": "تنظیمات",
      "speed_test": "تست سرعت",
      "notification": "اعلان",
      "language": "زبان",
      "protected_apps": "اضافه کردن همه برنامه‌ها",
      "connection_report": "گزارش اتصال",
      "terms_&_policy": "شرایط و قوانین",
      "privacy_policy": "سیاست حفظ حریم خصوصی",
      "share": "اشتراک‌گذاری",
      "subscriptions": "اشتراک‌ها",
      "my_account": "حساب من",
      "contact_support": "تماس با پشتیبانی",
      "upgrade_to_premium": "ارتقا به پرمیوم",
      "download": "دانلود",
      "upload": "آپلود",
      "locations": "مکان‌ها",
      "free": "رایگان",
      "premium": "پرمیوم",
      "loading_vpns": "در حال بارگیری وی‌پی‌ان‌ها... 😌",
      "loading_apps": "در حال بارگیری برنامه‌های نصب شده... 😌",
      "vpn_not_found": "وی‌پی‌ان پیدا نشد! 😔",
      "selecting_server": "در حال انتخاب سرور...",
      "progress": "پیشرفت",
      "time": "زمان",
      "save": "ذخیره",
      "no_ads": "بدون تبلیغات",
      "enjoy_ads": "از مرور بدون تبلیغات لذت ببرید",
      "fast": "سریع",
      "increase_connection_speed": "افزایش سرعت اتصال",
      "all_servers": "تمام سرورها",
      "access_all_server_worldwide": "دسترسی به تمام سرورها در سراسر جهان",
      "subscription_des": "برای خرید یک حساب پرمیوم، روی دکمه زیر کلیک کنید",
      "restore_purchase": "بازیابی خرید",
      "terms_of_use": "شرایط استفاده (EULA)",
      "buy_now": "همین حالا خرید کنید",
      "welcome_back": "خوش آمدید",
      "login_to_continue": "برای ادامه وارد شوید",
      "email": "ایمیل",
      "enter_your_valid_email": "ایمیل معتبر خود را وارد کنید",
      "password": "رمز عبور",
      "enter_your_password": "رمز عبور خود را وارد کنید",
      "forgot_password?": "رمز عبور را فراموش کرده‌اید؟",
      "sign_in": "ورود",
      "or_sign_in_with": "یا ورود با",
      "register": "ثبت نام",
      "register_to_continue": "برای ادامه ثبت نام کنید",
      "phone": "تلفن",
      "enter_your_phone_number": "شماره تلفن خود را وارد کنید",
      "name": "نام",
      "enter_your_name": "نام خود را وارد کنید",
      "already_have_an_account?": "قبلاً حساب دارید؟ ",
      "login": "ورود",
      "report_des":
          "این یک خلاصه از اطلاعات استفاده از ${Config.appName} هنگام اتصال است",
      "ip_address": "آدرس آی‌پی",
      "internet_provider": "ارائه‌دهنده اینترنت",
      "location": "مکان",
      "pin_code": "کد پین",
      "timezone": "منطقه زمانی",
      "logout": "خروج",
      "confirm_logout": "تأیید خروج",
      "logout_sure": "آیا مطمئن هستید که می‌خواهید خارج شوید؟",
      "yes": "بله",
      "no": "خیر",
      "clear": "پاک کردن",
      "delete_notification": "حذف اعلان",
      "delete_notification_sure": "آیا از حذف تمام اعلان‌ها مطمئن هستید؟",
      "notication_not_found": "اعلانی یافت نشد",
      "enter_key_des":
          "کلید لایسنس را برای فعال‌سازی ویژگی‌های پرمیوم وارد کنید",
      "licence_key": "کلید لایسنس",
      "enter_key": "کلید لایسنس را وارد کنید",
      "activate": "فعال‌سازی",
      "enter_code": "کد ۶ رقمی را وارد کنید",
      "otp_des": "کد ۶ رقمی که روی گوشی خود دریافت کرده‌اید را وارد کنید",
      "dont_have_an_account?": "حساب ندارید؟ ",
      "subscription_active": "طرح اشتراک شما اکنون فعال است",
      "time_balance": "موجودی زمان",
      "recharge_time": "زمان شارژ مجدد",
      "account_management": "مدیریت حساب",
      "no_premium": "بدون پرمیوم",
      "subscription_not_active": "اشتراک فعال نیست",
      "user_id": "شناسه کاربر",
      "devices": "دستگاه‌ها",
      "expiry_date": "تاریخ انقضا",
      "buy_account": "خرید حساب",
      "recharge": "شارژ",
      "trial_off": "دوره آزمایشی به پایان رسیده است",
      "please_register": "لطفاً برای ادامه ثبت‌نام کنید",
      "add_dns_record": "افزودن رکورد DNS",
      "edit_dns_record": "ویرایش رکورد DNS",
      "enter_dns_server": "وارد کردن سرور DNS",
      "enable_dns": "فعال کردن DNS",
      "dns_processed": "DNS توسط ماژول مرکزی پردازش شد",
      "vpn_dns": "VPN DNS (فقط IPv4/v6)",
      "mode": "حالت",
      "vpn_mode": "حالت VPN",
      "proxy_mode": "حالت پروکسی",
      "cancel": "لغو",
      "add_vpn": "افزودن VPN",
      "dns": "DNS",
      "dns_management": "مدیریت DNS"
    }
  };
  static Map<String, String> get current {
    final languageCode = Get.locale?.languageCode ?? Pref.lan;
    final translations = _translations[languageCode];

    if (translations == null) {
      // Handle missing translations, e.g., log an error or provide default translations
      print('Missing translations for language: $languageCode');
      return {}; // Or provide default translations
    }

    return translations;
  }

  @override
  Map<String, Map<String, String>> get keys => _translations;
}

class LanguageController extends GetxController {
  Locale _locale = Locale(Pref.lan); // Default language

  Locale get locale => _locale;

  String translate(String key) {
    return AppTranslations.current[key] ?? key;
  }

  void changeLocale(String languageCode) {
    Get.updateLocale(Locale(languageCode));
    _locale = Locale(languageCode);
    Pref.lan = languageCode;
    update(); // Notify listeners
  }
}
